services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-tanmay}"
    image: hatespeech-data-processing
    platform: linux/amd64
    container_name: hatespeech-data-processing-container
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./creds/gen-lang-client-0958213549-3c0d2210eba7.json
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-tanmay}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME:-tanmay}/.config/gcloud
    ports:
      - 8888:8888
      - 8000:8000

    ipc: host
    init: true


