version: "3.8"

services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-tanmay}"
    image: hatespeech-data-preparation
    platform: linux/amd64
    container_name: hateSpeech-data-preparation-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-tanmay}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME:-tanmay}/.config/gcloud
    ports:
      - 8080:8080

    ipc: host
    init: true


